### ISSUE TITLE
ERROR:  invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by mkastner** [ricardochimal/taps#110]
Maybe someone can help me on this;

Receiving schema
Schema:          0% |                                          | ETA:  --:--:--
Schema:          4% |=                                         | ETA:  00:00:44
Schema:          8% |===                                       | ETA:  00:00:36
Schema:         13% |=====                                     | ETA:  00:00:32
Schema:         17% |=======                                   | ETA:  00:00:27
Schema:         21% |========                                  | ETA:  00:00:24
Schema:         26% |==========                                | ETA:  00:00:21
Schema:         30% |============                              | ETA:  00:00:19
Schema:         34% |==============                            | ETA:  00:00:18
Schema:         39% |================                          | ETA:  00:00:17
Schema:         43% |==================                        | ETA:  00:00:16
Schema:         47% |===================                       | ETA:  00:00:15
Schema:         52% |=====================                     | ETA:  00:00:14
Schema:         56% |=======================                   | ETA:  00:00:13
Schema:         60% |=========================                 | ETA:  00:00:11
Schema:         65% |===========================               | ETA:  00:00:10
Schema:         69% |============================              | ETA:  00:00:08
Schema:         73% |==============================            | ETA:  00:00:07
Schema:         78% |================================          | ETA:  00:00:06
Schema:         82% |==================================        | ETA:  00:00:04
Schema:         86% |====================================      | ETA:  00:00:03
Schema:         91% |======================================    | ETA:  00:00:02
Schema:         95% |=======================================   | ETA:  00:00:01
Schema:        100% |==========================================| Time: 00:00:27
Receiving data
23 tables, 4,600 records
ads:           100% |==========================================| Time: 00:00:00
/Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in `async_exec': PG::Error: ERROR:  invalid byte sequence for encoding "UTF8": 0xdc62 (Sequel::DatabaseError)
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in`block (2 levels) in execute'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/logging.rb:28:in `log_yield'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in`block in execute'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:158:in `check_disconnect_errors'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in`execute'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:240:in `block (2 levels) in execute'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/connection_pool/threaded.rb:71:in`hold'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/connecting.rb:226:in `synchronize'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:240:in`block in execute'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:261:in `check_database_errors'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:238:in`execute'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/query.rb:71:in `execute_dui'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:552:in`execute_dui'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in `block (2 levels) in import'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in`each'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in `block in import'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/query.rb:223:in`_transaction'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/query.rb:209:in `block in transaction'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/connection_pool/threaded.rb:84:in`hold'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/connecting.rb:226:in `synchronize'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/database/query.rb:207:in`transaction'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in `import'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/data_stream.rb:315:in`import_rows'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/data_stream.rb:142:in `fetch_remote'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:308:in`block in pull_data_from_table'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:301:in `loop'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:301:in`pull_data_from_table'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:284:in `block in pull_data'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:278:in`each'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:278:in `pull_data'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:253:in`block in run'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:203:in `call'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:203:in`catch_errors'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/operation.rb:246:in `run'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/cli.rb:172:in`clientxfer'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/cli.rb:39:in `pull'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/cli.rb:27:in`run'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/gems/taps-0.3.24/bin/taps:6:in `<top (required)>'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/bin/taps:19:in`load'
    from /Users/kastner/.rvm/gems/ruby-1.9.3-p125/bin/taps:19:in `<main>'

**Comment by jrmyward** [comment]
I had a similar issue. It seemed to be related to the mysql encoding. I fixed it by specifying the encoding on the mysql database when I executed the <code>taps server</code> command. Example:

<pre>
<code>taps server mysql://root@localhost/example_database?encoding=UTF8 httpuser httppassword</code>
</pre>


Best of luck!

**Comment by RobWu** [comment]
Helped me, thanks

**Comment by ajahongir** [comment]
thanks, helped)

**Comment by jathayde** [comment]
This helped me with the same issue. Thanks!

**Comment by lou** [comment]
Thanks a lot, it helped!

**Comment by mattstone** [comment]
Thank you for that!

**Comment by fsainz** [comment]
thanks a lot!
