### ISSUE TITLE
SQlite3 required but not in dependencies

### ISSUE THREAD

**Issue by jbartosik** [ricardochimal/taps#116]
Taps needs Sqlite3 gem to work but it is not in dependencies. Please add sqlite3 to dependencies (or remove need for it).

How to reporduce
1) Make a new directory.
2) Put 

```
gem 'taps'
```

in Gemfile in the new directory.

3). Run

```
bundle install
```

in the directory

4) Run

```
taps
```

in the directory

The following error will appear (I removed bits about my system):

```
(dir)/gems/taps-0.3.24/lib/taps/cli.rb:10:in `require': cannot load such file -- sqlite3         (LoadError)
    from(dir)/gems/ruby-1.9.3-p125/gems/taps-0.3.24/lib/taps/cli.rb:10:in `<top (required)>'
    from(dir)/gems/ruby-1.9.3-p125/gems/taps-0.3.24/bin/taps:4:in `require'
    from(dir)/gems/ruby-1.9.3-p125/gems/taps-0.3.24/bin/taps:4:in `<top (required)>'
    from (dir)/ruby-1.9.3-p125/bin/taps:19:in `load'
    from (dir)/ruby-1.9.3-p125/bin/taps:19:in `<main>'
    from (dir)/.rvm/gems/ruby-1.9.3-p125/bin/ruby_bundler_wrapper:23:in `eval'
    from (dir)/.rvm/gems/ruby-1.9.3-p125/bin/ruby_bundler_wrapper:23:in `<main>
```

**Comment by skull-squadron** [comment]
:+1:
