### ISSUE TITLE
Error while importing data from mysql to postgresql

### ISSUE THREAD

**Issue by afzallakdawala** [ricardochimal/taps#132]
taps server mysql://root:afzal@localhost/ticket_users afzal afzal
## /home/afzal/.rvm/gems/ruby-1.9.3-p429/bundler/gems/taps-93bd2723df7f/lib/taps/cli.rb:10:in `require': cannot load such file -- sqlite3 (LoadError)

```
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bundler/gems/taps-93bd2723df7f/lib/taps/cli.rb:10:in `<top (required)>'
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bundler/gems/taps-93bd2723df7f/bin/taps:4:in `require'
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bundler/gems/taps-93bd2723df7f/bin/taps:4:in `<top (required)>'
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/taps:23:in `load'
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/taps:23:in `<main>'
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by afzallakdawala** [comment]
how can i resolve this issue????

**Comment by supermomonga** [comment]
try `gem install sqlite3`.
