### ISSUE TITLE
Pushing a db with a table with a Date field

### ISSUE THREAD

**Issue by greenplastik** [ricardochimal/taps#25]
Ruby: 1.9.2dev
Rails: 3.0 beta3
Taps: 0.3.4

I have an app using a sqlite3 db with a Users table with a 'birthday' field of type 'date'. When I try to push the db with 'heroku db:push', the push proceeds until it stops at uploading the users table, and I get the following error:

```
Taps Server Error: instance of Date needs to have method `marshal_load'
```

At the time of the error, the db had only one user (Testy McGee, who didn't have a birthday entered in the db). After I removed the 'birthday' field with a migration, the error went away.

Obviously the users.table has the usual timestamp fields, which are of type 'datetime'. There does not appear to be an issue with the 'datetime' fields.

The migration I used to add the 'date' field was as follows:
    class AddBirthdayToUsers < ActiveRecord::Migration
        def self.up
            add_column :users, :birthday, :date
        end
        def self.down
            remove_column :users, :birthday
        end
    end

Wonder if the fault is on my end. Appreciate the help.

**Comment by ricardochimal** [comment]
can you provide a link to the sqlite3 db? it would probably help me see if it's something that's being done different in ruby 1.9.2

**Comment by ricardochimal** [comment]
Can you try taps 0.3.6 and see if it solves your issue?

**Comment by ricardochimal** [comment]
I think something changed in ruby 1.9.x. for some reason DateTime's can't be marshal'd natively (???!).  I'll investigate some more to see what can be done.

**Comment by alfonsoadriasola-zz** [comment]
I"m getting the same  error pulling a DB 

Rails 2.3.5
Ruby 1.9.1
Taps 0.3.6

**Comment by mdoldy** [comment]
I have a similar problem pulling from Heroku.

data_stream.rb:183:in 'load': class DateTime needs to have method '_load' (TypeError)
Ruby 1.9.1, Rails 2.3.5, Taps 0.3.6.

**Comment by plukevdh** [comment]
same here.

**Comment by textual** [comment]
same here...pulling from heroku

Rails 2.3.5
Ruby 1.9.1
Taps 0.3.6

/usr/local/lib/ruby/gems/1.9.1/gems/taps-0.3.6/lib/taps/data_stream.rb:183:in `load': class DateTime needs to have method`_load' (TypeError)

**Comment by n2linux** [comment]
Same here when trying to push to heroku.

Rails 3
Ruby 1.9.1
Taps 0.3.6
Heroku 1.9.9

---

!!! Caught Server Exception
HTTP CODE: 500

## Taps Server Error: instance of DateTime needs to have method `marshal_load'

**Comment by ricardochimal** [comment]
a work around at the moment is simply to use ruby 1.8.7 when using taps, I'm still investigating the marshal_load stuff with ruby 1.9.

**Comment by kylefox** [comment]
I just encountered this error today as well.

**Comment by wizardwerdna** [comment]
I hit it as well

**Comment by peterpunk** [comment]
I have the same error. Im using rvm and switch to 1.8.7 do the pull and then back to 1.9.1

**Comment by swrobel** [comment]
Same here:
Sqlite 3.6.22
Rails 2.3.8
Ruby 1.9.1
Taps 0.3.9
Heroku 1.9.10

Of note: I don't have any columns of type "date" just "datetime"

**Comment by alfonsoadriasola-zz** [comment]
been chasing this all day to day ; has anyone seen this in trying to get rvm to play nice with the 1.8.7 workaround?

.rvm/gems/ruby-1.8.7-p174/gems/taps-0.2.23/lib/taps/config.rb:6:in `version_yml': uninitialized constant Taps::YAML

**Comment by ricardochimal** [comment]
alfonsoadriasola: you need to update your taps version. you're using a really old version.  This ticket is in regards to taps 0.3.x

**Comment by alfonsoadriasola-zz** [comment]
dependency nightmare allright, i'm pulling from a heroku db, heroku 1.9 uses taps 0.3.X which as you know is hosed because of Ruby 1.9.1 Marshal bug.  rvm 1.8.7 heroku needs to be 1.8 , which uses taps 0.2.23..
[UPDATE this was wrong on my part , nix]

**Comment by ricardochimal** [comment]
you can use heroku 1.9 with ruby 1.8, heroku gem's version number has nothing to do with the ruby version

**Comment by alfonsoadriasola-zz** [comment]
I take that back, must have been tired..  rvm 1.8.7 + heroku 1.9,11 + taps 0.3.9 worked
(phew)

**Comment by dominiclovell** [comment]
I had this issue on Rails 3, Heroku 1.9.13, Taps 0.3.11, and Ruby ruby-1.9.2-head, I had to revert back to Ruby 1.8.7 and then did a 'heroku db:push' and it worked

**Comment by sorenburkhart** [comment]
Ran into the same error while doing Michael Hartl's RoR tutorial.  

Rails: Rails 3.0.0.rc
Heroku: 1.9.13
Taps: 0.3.11
Ruby: ruby-1.9.2-head

schema file:
ActiveRecord::Schema.define(:version => 20100807162002) do

  create_table "microposts", :force => true do |t|
    t.string   "content"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end

when running 'heroku db:push' I get:

Loaded Taps v0.3.11
Auto-detected local database: sqlite://db/development.sqlite3
Warning: Data in the app 'warm-ice-56' will be overwritten and will not be recoverable.
Are you sure you wish to continue? (y/n)? y
Sending schema
Schema:        100% |==========================================| Time: 00:00:02
Sending indexes
schema_migrat: 100% |==========================================| Time: 00:00:00
Sending data
3 tables, 5 records
schema_migrat: 100% |==========================================| Time: 00:00:00
users:           0% |                                          | ETA:  --:--:--
Saving session to push_201008070931.dat..
!!! Caught Server Exception

HTTP CODE: 500
Taps Server Error: instance of DateTime needs to have method `marshal_load'
./lib/taps/data_stream.rb:190:in`load'./lib/taps/data_stream.rb:190:in `parse_encoded_data'./lib/taps/data_stream.rb:152:in`fetch_remote_in_server'./lib/taps/server.rb:55:in `POST /sessions/:key/push/table'./lib/taps/db_session.rb:15:in`conn'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sequel-3.13.0/lib/sequel/database/connecting.rb:73:in `connect'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sequel-3.13.0/lib/sequel/core.rb:111:in`connect'./lib/taps/db_session.rb:14:in `conn'./lib/taps/server.rb:52:in`POST /sessions/:key/push/table'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:863:in`route'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:521:in`route_eval'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:497:in`catch'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:476:in`each'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:601:in`dispatch!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in`instance_eval'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in`catch'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:411:in`call!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/auth/basic.rb:25:in`call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in`synchronize'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'/home/heroku_rack/lib/static_assets.rb:9:in`call'/home/heroku_rack/lib/last_access.rb:25:in `call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/urlmap.rb:47:in`call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in `each'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in`call'/home/heroku_rack/lib/date_header.rb:14:in `call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/builder.rb:77:in`call'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:74:in`catch'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:57:in`process'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'/usr/ruby1.8.7/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'/usr/ruby1.8.7/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in`start'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/controllers/controller.rb:80:in`start'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/runner.rb:177:in `send'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/runner.rb:177:in`run_command'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/runner.rb:143:in `run!'/home/slugs/150602_21d6549_44dc/mnt/.gems/gems/thin-1.2.7/bin/thin:6/usr/ruby1.8.7/bin/thin:19:in`load'/usr/ruby1.8.7/bin/thin:19

**Comment by fabbrikk** [comment]
I'm new to ruby&rails and I'm in the very exact situation of @sorenburkhart.
I have solved the problem in this way:
first switch to the 1.8.7 version of ruby with rvm:

rvm ruby-1.8.7-p299

then install the heroku and taps gems:

gem install heroku
gem install taps

then push the db contents to heroku:

heroku db:push

Now you can switch back to the latest version of ruby with:

rvm default

or

rvm ruby-1.9.2-rc2

I hope this will help someone!

**Comment by AlanMcCann** [comment]
Hi fabbrikk:
Thanks for the great tip.

I'm experiencing the same issue (thought I also tested with ruby 1.9.2-head (like sorenburkhart above)

It's obviously a challenging issue to deal with (I can't imagine Heroku would think it's unimportant)

**Comment by nextofsearch** [comment]
I am on the same page.
I will try fabbrikk's method tomorrow.
Thanks,

**Comment by keegnotrub** [comment]
Could this maybe be changed so that DateTime marshals through the String object (which does marshal in 1.9). I'd think you could just use strftime and strptime,

**Comment by nextofsearch** [comment]
Will this be fixed eventually??

**Comment by markbates** [comment]
Is there any update on this?

**Comment by SomeWare** [comment]
@fabbrikk! You save my day (or night, really)! Thanks!

**Comment by xaviershay** [comment]
The fundamental problem is using Marshal to send data is broken - It is not guaranteed to be compatible across ruby versions. Taps needs to be changed to use an agnostic serialization mechanism (yaml?)

**Comment by Sjors** [comment]
Getting the same error when trying to pull my Heroku database:

 heroku db:pull 
 [....]
 points:        100% |==========================================| Time:  00:00:00
 Receiving data
 9 tables, 1,882 records
 schema_migrat: 100% |==========================================| Time: 00:00:02
 Error encountered loading data, wrote the data chunk to dump.49065.dat --:--:--
/Users/sjors/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.19/lib/taps/data_stream.rb:192:in `load': class DateTime needs to have method`_load' (TypeError)

Mac OS 10.6.6
Rails 3.0.4
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0]
taps (0.3.19)
sqlite3 (1.3.3)
sqlite3-ruby (1.3.3)

I tried to "solve" the problem by switching to MySQL:
mysql (2.8.1)

But that results in the same error.

**Comment by Sjors** [comment]
Using ruby 1.8.7 just for the database pull works for me. I only tried it for MySQL:
rvm install ruby-1.8.7-p302
gem install heroku
gem install taps 
gem install mysql
