### ISSUE TITLE
SQLite3::SQLException: unrecognized token: "`"

### ISSUE THREAD

**Issue by krisalyssa** [ricardochimal/taps#28]
Both Ruby 1.8.6 and 1.9.1, taps 0.3.5, sqlite3-ruby 1.25 on top of sqlite3 3.6.23.1 installed via MacPorts.

I get this error consistently when running:

taps server sqlite://db/development.sqlite3 user pass

-d doesn't provide any more detail. Is there something else I can do or set to provide more output?

**Comment by ricardochimal** [comment]
can you try typing 

  schema dump sqlite://db/development.sqlite3

**Comment by krisalyssa** [comment]
```
craigc@tabitha:~/Projects/Rails/ipmap$ schema dump sqlite://db/development.sqlite3
/Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sqlite3-ruby-1.2.5/lib/sqlite3/errors.rb:62:in `check': SQLite3::SQLException: unrecognized token: "`" (Sequel::DatabaseError)
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sqlite3-ruby-1.2.5/lib/sqlite3/statement.rb:40:in `initialize'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sqlite3-ruby-1.2.5/lib/sqlite3/database.rb:160:in `new'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sqlite3-ruby-1.2.5/lib/sqlite3/database.rb:160:in `prepare'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sqlite3-ruby-1.2.5/lib/sqlite3/database.rb:251:in `query'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sequel-3.10.0/lib/sequel/adapters/sqlite.rb:83:in `execute'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sequel-3.10.0/lib/sequel/adapters/sqlite.rb:98:in `_execute'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sequel-3.10.0/lib/sequel/connection_pool/threaded.rb:84:in `hold'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/sequel-3.10.0/lib/sequel/database.rb:535:in `synchronize'
     ... 9 levels...
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/taps-0.3.5/bin/../lib/taps/schema.rb:13:in `dump'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/gems/taps-0.3.5/bin/schema:29
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/bin/schema:19:in `load'
    from /Users/craigc/.rvm/gems/ruby-1.9.1-p378/bin/schema:19
```

**Comment by krisalyssa** [comment]
Same results with Ruby 1.8.6.
