### ISSUE TITLE
JSON.parsed fed non-JSON filespec

### ISSUE THREAD

**Issue by jds13** [ricardochimal/taps#36]
JSON.parsed is called in lib\taps\operation.rb:409.  In my case, the argument passed is this:
   c:/program files/ruby/lib/ruby/gems/1.9.1/gems/taps-0.3.6/lib/taps/../../bin/schema.cmd
       'indexes_individual'
       'mysql://root:password@localhost/app?encoding=utf8'
(line wrapped for clarity)

JSON.parsed complains that
c:/program files/ruby/lib/ruby/gems/1.9.1/gems/json_pure-1.4.3/lib/json/pure/parser.rb:143:in `parse': source 'c:/program files/rub' not in JSON! (JSON::ParserError)
        from c:/program files/ruby/lib/ruby/gems/1.9.1/gems/json_pure-1.4.3/lib/json/common.rb:146:in`parse'
        from c:/program files/ruby/lib/ruby/gems/1.9.1/gems/taps-0.3.6/lib/taps/operation.rb:411:in `push_indexes'
        from c:/program files/ruby/lib/ruby/gems/1.9.1/gems/taps-0.3.6/lib/taps/operation.rb:387:in`run'

I'm running json_pure 1.4.3 and ricardochimal-taps-v0.3.6-1-g9141fbe.zip
Thank you for any help you might be able to provide.

**Comment by ricardochimal** [comment]
http://github.com/ricardochimal/taps/commit/9141fbe8d2e3eb58f49d0c725ab36d768d239730   can you try making this change to your local taps installation and see if it works for you?
