### ISSUE TITLE
Starting server fails....union: can't convert Array into String (TypeError)

### ISSUE THREAD

**Issue by webandy** [ricardochimal/taps#42]
Hello. I installed taps on my Ubuntu 8.04 slice hoping to move the db schema + data to a local copy. I am unable to start the server. I installed the latest version of taps and an older version of taps I needed to get working on my local Mac with Heroku (which happened to be version 0.2.26). 

Here is what the older version install looked like:
sudo gem install taps -v 0.2.26 --no-rdoc --no-ri
Successfully installed thor-0.9.9
Successfully installed rest-client-1.3.1
Successfully installed sequel-3.0.0
Successfully installed taps-0.2.26

If I uninstall that and get the latest:
$ sudo gem install taps
Successfully installed taps-0.3.11

I have the following versions of rack and sinatra if that makes a difference?
rack (1.2.1...)
sinatra (1.0...)

$ taps server "mysql://localhost/mydb?user=user&password=pwd" foo bar123
/usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/utils.rb:138:in `union': can't convert Array into String (TypeError)
    from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/utils.rb:138
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/request.rb:1
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/rack-1.2.1/lib/rack/showexceptions.rb:3
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
     ... 14 levels...
    from /usr/lib/ruby/gems/1.8/gems/thor-0.9.9/lib/thor.rb:78:in `start'
    from /usr/lib/ruby/gems/1.8/gems/taps-0.2.26/bin/taps:13
    from /usr/bin/taps:19:in`load'
    from /usr/bin/taps:19

I'm referencing this blog post:
http://adam.heroku.com/past/2009/2/11/taps_for_easy_database_transfers/

Anything else I can try?

**Comment by ricardochimal** [comment]
can you try uninstalling rack 1.2.1 and installing rack 1.1.0  and see if it works?

**Comment by webandy** [comment]
I just updated the Ruby on the machine since it was 1.8.6 and thought it might be a 1.8.6 vs. 1.8.7 issue perhaps (just a guess) $ ruby -v
ruby 1.8.7 (2010-06-23 patchlevel 299) [x86_64-linux]
Same issue though unfortunately.

**Comment by webandy** [comment]
Yah! Removing rack-1.2.1 and install rack 1.1.0 fixed the issue. Thanks for the speedy response!

**Comment by gerrit** [comment]
I'm having the same issue. Unfortunately rack 1.2 is required by another library I've got installed. Couldn't taps just load the right version by itself?
