### ISSUE TITLE
unable to open database file (Sequel::DatabaseConnectionError)

### ISSUE THREAD

**Issue by jeffshadap** [ricardochimal/taps#46]
$ heroku db:push
Loaded Taps v0.3.11
Auto-detected local database: sqlite://db/development.sqlite3
Warning: Data in the app 'afternoon-autumn-56' will be overwritten and will not be recoverable.
Are you sure you wish to continue? (y/n)? y
Sending schema
c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:36:in `initialize': SQLite3::CantOpenExceptio
n: unable to open database file (Sequel::DatabaseConnectionError)
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:36:in`new'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:36:in `connect'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/misc.rb:44
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool.rb:92:in`call'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool.rb:92:in `make_new'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:126:in`make_new'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:112:in `available'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:102:in`acquire'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:146:in `sync'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:146:in`synchronize'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:146:in `sync'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:101:in`acquire'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:74:in `hold'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/connecting.rb:189:in`synchronize'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:115:in `_execute'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:80:in`execute'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:392:in `execute'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:272:in`fetch_rows'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:101:in `each'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:248:in`map'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:248:in `map'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/shared/sqlite.rb:249:in`parse_pragma'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/shared/sqlite.rb:270:in `schema_parse_tabl
e'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/query.rb:129:in`schema'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/extensions/schema_dumper.rb:57:in `dump_table_schem
a'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/bin/../lib/taps/schema.rb:22:in`dump_table'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/connecting.rb:73:in `connect'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/core.rb:111:in`connect'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/bin/../lib/taps/schema.rb:18:in `dump_table'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/bin/schema:32
Schema:        100% |==========================================| Time: 00:00:03
c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:36:in`initialize': SQLite3::CantOpenExceptio
n: unable to open database file (Sequel::DatabaseConnectionError)
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:36:in `new'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:36:in`connect'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/misc.rb:44
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool.rb:92:in `call'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool.rb:92:in`make_new'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:126:in `make_new'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:112:in`available'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:102:in `acquire'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:146:in`sync'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:146:in `synchronize'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:146:in`sync'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:101:in `acquire'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/connection_pool/threaded.rb:74:in`hold'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/connecting.rb:189:in `synchronize'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:115:in`_execute'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:80:in `execute'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:392:in`execute'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/sqlite.rb:272:in `fetch_rows'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:101:in`each'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:248:in `map'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/dataset/actions.rb:248:in`map'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/adapters/shared/sqlite.rb:122:in `tables'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/bin/../lib/taps/schema.rb:41:in`indexes_individual'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/database/connecting.rb:73:in `connect'
        from c:/ruby/lib/ruby/gems/1.8/gems/sequel-3.13.0/lib/sequel/core.rb:111:in`connect'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/bin/../lib/taps/schema.rb:40:in `indexes_individual'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/bin/schema:36
c:/ruby/lib/ruby/gems/1.8/gems/json_pure-1.4.3/lib/json/pure/parser.rb:146:in`parse': source did not contain any JSON!
(JSON::ParserError)
        from c:/ruby/lib/ruby/gems/1.8/gems/json_pure-1.4.3/lib/json/common.rb:146:in `parse'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/lib/taps/operation.rb:410:in`push_indexes'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/lib/taps/operation.rb:388:in `run'
        from c:/ruby/lib/ruby/gems/1.8/gems/taps-0.3.11/lib/taps/cli.rb:164:in`clientxfer'
        from c:/ruby/lib/ruby/gems/1.8/gems/heroku-1.9.13/lib/heroku/commands/db.rb:156:in `taps_client'
        from c:/ruby/lib/ruby/gems/1.8/gems/heroku-1.9.13/lib/heroku/commands/db.rb:13:in`push'
        from c:/ruby/lib/ruby/gems/1.8/gems/heroku-1.9.13/lib/heroku/command.rb:48:in `send'
        from c:/ruby/lib/ruby/gems/1.8/gems/heroku-1.9.13/lib/heroku/command.rb:48:in`run_internal'
        from c:/ruby/lib/ruby/gems/1.8/gems/heroku-1.9.13/lib/heroku/command.rb:20:in `run'
        from c:/ruby/lib/ruby/gems/1.8/gems/heroku-1.9.13/bin/heroku:13
        from c:/ruby/bin/heroku:19:in`load'
        from c:/ruby/bin/heroku:19

**Comment by lloydb** [comment]
I have the same problem - did you manage to solve it?

**Comment by mrdizzy** [comment]
Same problem here too.

**Comment by lloydb** [comment]
I updated heroku and taps gems and it is now working fine.
