### ISSUE TITLE
taps does not appear to work on MacOSX 10.6 "Snow Leopard"

### ISSUE THREAD

**Issue by wolfch** [ricardochimal/taps#67]
This issue stems from not being able to perform "heroku db:push" of a local app.  However the exact same error is reproducible simply by attempting to invoke the "taps" executable:

```
$ taps
/Library/Ruby/Gems/1.8/gems/sqlite3-ruby-1.3.2/lib/sqlite3/sqlite3_native.bundle: dlsym(0x101426260, Init_sqlite3_native): symbol not found - /Library/Ruby/Gems/1.8/gems/sqlite3-ruby-1.3.2/lib/sqlite3/sqlite3_native.bundle     (LoadError)
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/sqlite3-ruby-1.3.2/lib/sqlite3.rb:6
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/taps-0.3.14/bin/../lib/taps/config.rb:2
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/taps-0.3.14/bin/../lib/taps/cli.rb:5
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/taps-0.3.14/bin/taps:4
from /usr/bin/taps:19:in `load'
from /usr/bin/taps:19
```

Note that the sqlite3-ruby and taps gems are installed:
    $ gem list -d sqlite3
    sqlite3-ruby (1.3.2, 1.2.4)
    Installed at (1.3.2): /Library/Ruby/Gems/1.8
                      (1.2.4): /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8

```
$ gem list -d taps
taps (0.3.14)

$ irb
>> require 'sqlite3'
=> true
>> db = SQLite3::Database.new('/tmp/bugus.db')
=> #<SQLite3::Database:0x1011274b8>
>> puts db.execute('select sqlite_version()')
3.6.12
```

Plus I have a local instance of Radiant running, using sqlite3 just fine.  I have the latest Xcode installed.  To me, the problem seems to be isolated to taps on Snow Leopard.

**Comment by turadg** [comment]
FWIW, it works fine with Homebrew on Snow Leopard:

```
$ taps
Options
=======
server    Start a taps database import/export server
pull      Pull a database from a taps server
push      Push a database to a taps server
version   Taps version

Add '-h' to any command to see their usage
```

taps 0.3.15.

**Comment by wolfch** [comment]
Yes, 0.3.15 works for me too.  The issue was when I was using 0.3.14, which was the latest when I first tried it and that one didn't work.  I also had to remove sqlite3-gem to make it work with sqlite.
