### ISSUE TITLE
schema parsing returned no columns, table probably doesn't exist

### ISSUE THREAD

**Issue by jeffshadap** [ricardochimal/taps#71]
Sending schema
e:/Ruby192/lib/ruby/gems/1.9.1/gems/sequel-3.17.0/lib/sequel/database/query.rb:163:in `schema': schema parsing returned
no columns, table probably doesn't exist (Sequel::Error)
        from e:/Ruby192/lib/ruby/gems/1.9.1/gems/sequel-3.17.0/lib/sequel/extensions/schema_dumper.rb:57:in`dump_table_
schema'
        from e:/Ruby192/lib/ruby/gems/1.9.1/gems/taps-0.3.15/lib/taps/schema.rb:21:in `block in dump_table'
        from e:/Ruby192/lib/ruby/gems/1.9.1/gems/sequel-3.17.0/lib/sequel/database/connecting.rb:76:in`connect'
        from e:/Ruby192/lib/ruby/gems/1.9.1/gems/sequel-3.17.0/lib/sequel/core.rb:119:in `connect'
        from e:/Ruby192/lib/ruby/gems/1.9.1/gems/taps-0.3.15/lib/taps/schema.rb:17:in`dump_table'
        from e:/Ruby192/lib/ruby/gems/1.9.1/gems/taps-0.3.15/bin/schema:32:in `<main>'
Schema:        100% |==========================================| Time: 00:00:04
Sending data
1 tables, 0 records
tbl1:          100% |==========================================| Time: 00:00:00
Resetting sequences

My setup is 
OS- Windows
ruby - 1.9.2
gem -1.3.7
taps -0.3.15

**Comment by dsaronin** [comment]
I've gotten same error while trying to pull from heroku.
    $ heroku db:pull postgres://user:password@localhost/<database>
    !!! Caught Server Exception
    HTTP CODE: 500
    Taps Server Error: schema parsing returned no columns, table probably doesn't exist

looks like it failed at schema_migrations table which only has one column. I've double-checked the table and it's good and all data can be retrieved. 

Local configuration: Ubuntu 10.10, Postgres 8, taps 0.3.15, REE1.8.7

```
/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sequel-3.17.0/lib/sequel/database/query.rb:163:in `schema'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/utils.rb:154:in `primary_key'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/utils.rb:164:in `order_by'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/data_stream.rb:66:in `order_by'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/data_stream.rb:78:in `fetch_rows'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/data_stream.rb:116:in `fetch'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/server.rb:159:in `POST /sessions/:key/pull/table'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/db_session.rb:15:in `conn'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sequel-3.17.0/lib/sequel/database/connecting.rb:76:in `connect'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sequel-3.17.0/lib/sequel/core.rb:119:in `connect'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/db_session.rb:14:in `conn'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/lib/taps/server.rb:156:in `POST /sessions/:key/pull/table'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `route'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/rack-1.2.1/lib/rack/auth/basic.rb:25:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'/home/heroku_rack/lib/static_assets.rb:9:in `call'/home/heroku_rack/lib/last_access.rb:15:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/rack-1.2.1/lib/rack/urlmap.rb:47:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/rack-1.2.1/lib/rack/urlmap.rb:41:in `each'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/rack-1.2.1/lib/rack/urlmap.rb:41:in `call'/home/heroku_rack/lib/date_header.rb:14:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/rack-1.2.1/lib/rack/builder.rb:77:in `call'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/controllers/controller.rb:80:in `start'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/runner.rb:177:in `send'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/runner.rb:177:in `run_command'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/lib/thin/runner.rb:143:in `run!'/app/831593ba-d84d-4368-951b-a5c847cb394b/home/.bundle/gems/ruby/1.8/gems/thin-1.2.7/bin/thin:6/usr/ruby1.8.7/bin/thin:19:in `load'/usr/ruby1.8.7/bin/thin:19
```

**Comment by MaffooClock** [comment]
I'm also running into this.

Server: Ubuntu 10.04 LTS + Ruby 1.9.2p180 (RVM) + MySQL 5

`taps server mysql2://dbuser:dbpass@localhost/moxie-rails httpuser httppass`

Client: Mac OS X Lion + Ruby 1.9.2p180 (RVM) + SQLite3

```
Matts-MacBook-Pro-4:Moxie mclark$ taps pull sqlite:./db/moxie.sqlite3 http://httpuser:httppass@172.17.43.240:5000
Receiving schema
Schema:          0% |                                          | ETA:  --:--:--
Schema:          7% |==                                        | ETA:  00:00:24
Schema:         14% |=====                                     | ETA:  00:00:21
Schema:         21% |========                                  | ETA:  00:00:19
Schema:         28% |===========                               | ETA:  00:00:18
Schema:         35% |==============                            | ETA:  00:00:16
Schema:         42% |=================                         | ETA:  00:00:13
Schema:         50% |=====================                     | ETA:  00:00:12
Schema:         57% |=======================                   | ETA:  00:00:10
Schema:         64% |==========================                | ETA:  00:00:08
Schema:         71% |=============================             | ETA:  00:00:06
Schema:         78% |================================          | ETA:  00:00:05
Schema:         85% |===================================       | ETA:  00:00:03
Schema:         92% |======================================    | ETA:  00:00:01
Schema:        100% |==========================================| Time: 00:00:24
Receiving data
14 tables, 2,800 records
/Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/sequel-3.20.0/lib/sequel/database/query.rb:163:in `schema': schema parsing returned no columns, table probably doesn't exist (Sequel::Error)
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/utils.rb:142:in `single_integer_primary_key'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/data_stream.rb:237:in `factory'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:280:in `block in pull_data'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:278:in `each'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:278:in `pull_data'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:253:in `block in run'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:203:in `call'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:203:in `catch_errors'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/operation.rb:246:in `run'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/cli.rb:171:in `clientxfer'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/cli.rb:38:in `pull'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/lib/taps/cli.rb:26:in `run'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/gems/taps-0.3.23/bin/taps:6:in `<top (required)>'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/bin/taps:19:in `load'
    from /Users/mclark/.rvm/gems/ruby-1.9.2-p180/bin/taps:19:in `<main>'
```

**Comment by urkle** [comment]
A Ha!!!

I fought with this for a while just now..  the KEY to solving the issue..   Specify an ABSOLUTE path instead of a relative path.

So.
taps pull sqlite:`pwd`/db/temp.sqlite3 .....
