### ISSUE TITLE
Taps forgets which sequel database adapter to use

### ISSUE THREAD

**Issue by dcunited001** [ricardochimal/taps#86]
About to look through the stack trace

David-Conners-MacBook-Pro:StartNorfolk davidconner$ heroku db:push
Loaded Taps v0.3.23
Auto-detected local database: postgres://testapp:testapp@127.0.0.1/startnorfolk_development?encoding=utf8
Warning: Data in the app 'startnorfolk' will be overwritten and will not be recoverable.

 !    WARNING: Potentially Destructive Action
 !    This command will affect the app: startnorfolk
 !    To proceed, type "startnorfolk" or re-run this command with --confirm startnorfolk

> startnorfolk
> Sending schema
> Schema:        100% |==========================================| Time: 00:00:30
> Sending indexes
> users:         100% |==========================================| Time: 00:00:00
> schema_migrat: 100% |==========================================| Time: 00:00:00
> slugs:         100% |==========================================| Time: 00:00:01
> seo_meta:      100% |==========================================| Time: 00:00:01
> refinery_sett: 100% |==========================================| Time: 00:00:00
> participants:  100% |==========================================| Time: 00:00:00
> roles_users:   100% |==========================================| Time: 00:00:01
> inquiries:     100% |==========================================| Time: 00:00:01
> blog_comments: 100% |==========================================| Time: 00:00:00
> sponsors:      100% |==========================================| Time: 00:00:00
> user_plugins:  100% |==========================================| Time: 00:00:01
> blog_categori: 100% |==========================================| Time: 00:00:00
> sponsorship_t: 100% |==========================================| Time: 00:00:00
> blog_categori: 100% |==========================================| Time: 00:00:00
> inquiry_types: 100% |==========================================| Time: 00:00:00
> page_parts:    100% |==========================================| Time: 00:00:01
> blog_posts:    100% |==========================================| Time: 00:00:00
> pages:         100% |==========================================| Time: 00:00:04
> page_part_tra: 100% |==========================================| Time: 00:00:00
> taggings:      100% |==========================================| Time: 00:00:01
> page_translat: 100% |==========================================| Time: 00:00:00
> participant_t: 100% |==========================================| Time: 00:00:00
> Sending data
> 27 tables, 213 records
> users:           0% |                                          | ETA:  --:--:--
> Saving session to push_201107122113.dat..
> !!! Caught Server Exception
> HTTP CODE: 500
> Taps Server Error: LoadError: no such file to load -- sequel/adapters/
> ["/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/core.rb:249:in `require'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/core.rb:249:in`block in tsk_require'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/core.rb:72:in `block in check_requiring_thread'", "<internal:prelude>:10:in`synchronize'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/core.rb:69:in `check_requiring_thread'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/core.rb:249:in`tsk_require'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/database/connecting.rb:25:in `adapter_class'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/database/connecting.rb:54:in`connect'", "/app/.bundle/gems/ruby/1.9.1/gems/sequel-3.20.0/lib/sequel/core.rb:119:in `connect'", "/app/lib/taps/db_session.rb:14:in`conn'", "/app/lib/taps/server.rb:91:in `block in <class:Server>'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:865:in`call'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:865:in `block in route'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:521:in`instance_eval'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:500:in`block (2 levels) in route!'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:497:in`block in route!'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:476:in`route!'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:411:in`block in call!'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:566:in`block in invoke'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:566:in`invoke'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:399:in`call'", "/app/.bundle/gems/ruby/1.9.1/gems/rack-1.2.1/lib/rack/auth/basic.rb:25:in `call'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:979:in`block in call'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'", "/app/.bundle/gems/ruby/1.9.1/gems/sinatra-1.0/lib/sinatra/base.rb:979:in`call'", "/home/heroku_rack/lib/static_assets.rb:9:in `call'", "/home/heroku_rack/lib/last_access.rb:15:in`call'", "/app/.bundle/gems/ruby/1.9.1/gems/rack-1.2.1/lib/rack/urlmap.rb:47:in `block in call'", "/app/.bundle/gems/ruby/1.9.1/gems/rack-1.2.1/lib/rack/urlmap.rb:41:in`each'", "/app/.bundle/gems/ruby/1.9.1/gems/rack-1.2.1/lib/rack/urlmap.rb:41:in `call'", "/home/heroku_rack/lib/date_header.rb:14:in`call'", "/app/.bundle/gems/ruby/1.9.1/gems/rack-1.2.1/lib/rack/builder.rb:77:in `call'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/connection.rb:76:in`block in pre_process'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/connection.rb:74:in`pre_process'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/connection.rb:42:in`receive_data'", "/app/.bundle/gems/ruby/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'", "/app/.bundle/gems/ruby/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/server.rb:156:in`start'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/controllers/controller.rb:80:in `start'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/runner.rb:177:in`run_command'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/lib/thin/runner.rb:143:in `run!'", "/app/.bundle/gems/ruby/1.9.1/gems/thin-1.2.7/bin/thin:6:in`<top (required)>'", "/usr/ruby1.9.2/bin/thin:19:in `load'", "/usr/ruby1.9.2/bin/thin:19:in`<main>'"]

**Comment by kevinmtrowbridge** [comment]
Also running into this issue.  This is the only result found via Google for that exception.  If I figure it out, I'll post the solution.

**Comment by dcunited001** [comment]
when i was running into this it was when i was trying to db:push to heroku.
 what had happened in believe was my # of dyno's had wound down to 0 for
that particular heroku app.  so i reset the number of dynos to 1 and that
fixed it.

**Comment by kevinmtrowbridge** [comment]
dcunited001 -- thanks for replying so quickly!  Unfortunately my problem was even more brain-dead, I had neglected to push the code up to the server, before trying to push the db up.  I've been doing a lot of Heroku work lately, so maybe that's my excuse.

Git push before trying to to use taps to populate the db, lesson duly noted.

**Comment by mortik** [comment]
Stil got that Problem and my app is pushed to Heroku and has one dyno

**Comment by rpmessner** [comment]
I was getting this error because I had not promoted (pg:promote) any database, so the ENV['DATABASE_URL'] was not set.

**Comment by econnally** [comment]
thanks @rpmessner your comment saved me

**Comment by spicymaya** [comment]
yes, @rpmessner , 8 months later and it saved me too :+1:
